#!/usr/bin/env python3
"""Apply publisher settings to the Xcode project generated by Apple's converter."""

from __future__ import annotations

import argparse
import json
import plistlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_root", type=Path)
    arguments = parser.parse_args()
    policy = json.loads((ROOT / ".appstore" / "policy.json").read_text())

    project_files = list(arguments.project_root.rglob("project.pbxproj"))
    if len(project_files) != 1:
        raise SystemExit(f"expected one project.pbxproj, found {len(project_files)}")
    project_file = project_files[0]
    text = project_file.read_text(encoding="utf-8")

    generated_host_id = (
        policy["bundle_identifier"].rsplit(".", 1)[0] + "." + policy["app_name"]
    )
    replacements = {
        generated_host_id: (policy["bundle_identifier"], {2}),
        generated_host_id + ".Extension": (
            policy["extension_bundle_identifier"],
            {0, 2},
        ),
        generated_host_id + "Tests": (policy["bundle_identifier"] + ".Tests", {0, 2}),
        generated_host_id + "UITests": (
            policy["bundle_identifier"] + ".UITests",
            {0, 2},
        ),
    }
    for old_identifier, (new_identifier, allowed_counts) in replacements.items():
        old = f"PRODUCT_BUNDLE_IDENTIFIER = {old_identifier};"
        new = f"PRODUCT_BUNDLE_IDENTIFIER = {new_identifier};"
        count = text.count(old)
        if count not in allowed_counts:
            raise SystemExit(
                f"converter output changed: found {count} occurrences of {old_identifier}"
            )
        text = text.replace(old, new)
    project_file.write_text(text, encoding="utf-8")

    host_plists = [
        path
        for path in arguments.project_root.rglob("Info.plist")
        if "Extension" not in str(path.parent)
    ]
    if len(host_plists) != 1:
        raise SystemExit(f"expected one host Info.plist, found {len(host_plists)}")
    with host_plists[0].open("rb") as file:
        info = plistlib.load(file)
    info["ITSAppUsesNonExemptEncryption"] = False
    with host_plists[0].open("wb") as file:
        plistlib.dump(info, file, sort_keys=True)

    print(project_file.parent.parent)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
